debug: true
local: true
restapi:
  probe_host: "0.0.0.0"
  probe_port: "16083"
grpc:
  logger_host: "localhost"
  logger_port: "18081"
  authentication_host: "localhost"
  authentication_port: "18084"